---
  html_document:
  toc: true
title: "Histogram Basics in ggplot2"
---

  ```{r setup, echo=FALSE, warning=FALSE,cache=FALSE}
library(knitr)
library(markdown)
options(width = 60)
opts_knit$set(upload = TRUE)
knitr::opts_chunk$set(cache=FALSE,warning=FALSE,fig.align='center',fig.width=8,fig.height=6,comment='')
```

# Create Individual Plots

```{r}
library(ggplot2)
width.histogram <- ggplot(iris,aes(Sepal.Width))+geom_histogram()
sepal.scatter <- ggplot(iris,aes(Sepal.Width,Sepal.Length))+geom_point()
```

<a href="#top">Back to top</a>

# bind_plots()

```{r}

# Source:
# https://stackoverflow.com/questions/24234791/plot-multiple-ggplot-plots-on-a-single-image-with-left-alignment-of-the-plots-an
rbind_max <- function(...){
  library(grid)
  gtl <- lapply(list(...), ggplotGrob)
  bind2 <- function (x, y){
    stopifnot(ncol(x) == ncol(y))
    if (nrow(x) == 0)
      return(y)
    if (nrow(y) == 0)
      return(x)
    y$layout$t <- y$layout$t + nrow(x)
    y$layout$b <- y$layout$b + nrow(x)
    x$layout <- rbind(x$layout, y$layout)
    x$heights <- gtable:::insert.unit(x$heights, y$heights)
    x$rownames <- c(x$rownames, y$rownames)
    x$widths <- grid::unit.pmax(x$widths, y$widths)
    x$grobs <- append(x$grobs, y$grobs)
    x
  }
  Reduce(bind2, gtl)
}
combined.plots <- do.call(rbind_max, list(length.histogram,width.histogram))
library(gtable)

panels <- combined.plots$layout$t[grep("panel", combined.plots$layout$name)]

# set the relative panel heights 1/3 for the top two
combined.plots$heights[panels] <- lapply(c(1,3), unit, "null")

grid.newpage()
grid.draw(combined.plots)
```

<a href="#top">Back to top</a>

  # More Resources
  - [Source as RMarkdown](https://github.com/rweyant/bertplot/blob/master/R/tutorials/ggplot-histogram/ggplot-histogram.Rmd))
- [docs.ggplot2.org](http://docs.ggplot2.org/0.9.3/geom_histogram.html)

